[package]
name = "sgf_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
thiserror = "1.0.56"
serde = { version = "1.0.195", features = ["derive"] }
